//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeEpidemias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clasificacion_paciente_epidemia
    {
        public int idclasificacion_paciente_epidemia { get; set; }
        public Nullable<int> idmedico { get; set; }
        public Nullable<int> idepidemia { get; set; }
        public Nullable<int> idpaciente { get; set; }
        public Nullable<int> nivelgravedad { get; set; }
        public Nullable<int> idsala { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual epidemia epidemia { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual paciente paciente { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
