//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeEpidemias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultorio_medico
    {
        public int idconsultorio_medico { get; set; }
        public Nullable<int> idconsultorio { get; set; }
        public Nullable<int> idmedico { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Consultorio Consultorio { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
