//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeEpidemias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expediente
    {
        public int idexpediente { get; set; }
        public Nullable<int> idpaciente { get; set; }
        public string codigo { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual paciente paciente { get; set; }
    }
}
