//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeEpidemias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordendetraslado
    {
        public int idordendetraslado { get; set; }
        public Nullable<int> idhospital { get; set; }
        public Nullable<int> idmedico { get; set; }
        public Nullable<int> idpaciente { get; set; }
        public Nullable<System.DateTime> fechaordentraslado { get; set; }
        public Nullable<System.DateTime> fechatraslado { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual hospital hospital { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
