//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeEpidemias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta_medica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receta_medica()
        {
            this.detalle_receta_medica = new HashSet<detalle_receta_medica>();
        }
    
        public int idreceta_medica { get; set; }
        public Nullable<int> idmedico { get; set; }
        public Nullable<int> idpaciente { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_receta_medica> detalle_receta_medica { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
