//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeEpidemias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idusuario { get; set; }
        public string nombreusuario { get; set; }
        public string contraseñausuario { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> idpermiso { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Permiso Permiso { get; set; }
    }
}
